// <auto-generated />
using IntersysJs.DataBase.DataBaseModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntersysJs.Migrations
{
    [DbContext(typeof(IntersysDb))]
    partial class IntersysDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntersysJs.DataBase.DataBaseModels.UserTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Tomasz",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Maria",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Katarzyna",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Katarzyna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Anna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Anna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Jan",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Tomasz",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Anna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Jan",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Katarzyna",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Tomasz",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Jan",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Jan",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Maria",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Jan",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Katarzyna",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Maria",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Maria",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Anna",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Katarzyna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Tomasz",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Tomasz",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Katarzyna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Anna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Jan",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Tomasz",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Anna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Maria",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Anna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Maria",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Jan",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Anna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Katarzyna",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Anna",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Maria",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Maria",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Katarzyna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Anna",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Jan",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Katarzyna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Anna",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Tomasz",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Anna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Anna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Tomasz",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Tomasz",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Jan",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Tomasz",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Maria",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Anna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Katarzyna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Katarzyna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Katarzyna",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Maria",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Maria",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Anna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Anna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Tomasz",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Maria",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Maria",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Katarzyna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Katarzyna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Anna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Anna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Maria",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Katarzyna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Anna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Katarzyna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Katarzyna",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Maria",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Jan",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Tomasz",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Anna",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Anna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Tomasz",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Maria",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Tomasz",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Jan",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Katarzyna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Maria",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Tomasz",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Jan",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Maria",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Katarzyna",
                            LastName = "Wójcik"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Jan",
                            LastName = "Krawczyk"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Katarzyna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Anna",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Jan",
                            LastName = "Wójcik"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
